- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/NavigationView.xaml
GitHub Issue (If applicable): unoplatform/uno.material#446
- Bugfix
added workaround for Ripple opacity issue
> fix(skia): added workaround for Ripple opacity issue

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/AnimationSamplePage.xaml
workaround https://github.com/unoplatform/uno/issues/5111
Animation sample are not working
When using absolute center for animations, element is miss-aligned on iOS
Use relative center instead
> fix: Workaround invalid absolute center for animation

- Uno.Gallery/Uno.Gallery.UWP/Views/Shell.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Shell.xaml.cs
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5143, fixes https://github.com/unoplatform/Uno.Gallery/issues/131, fixes #135
- Bugfix
CompactMode looks off.
Disabled the NavigationView compact mode by forcing the pane open and hiding the toggle button in expanded mode.
> fix: Disable NavigationView compact mode, make pane wider

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ProgressSamplePage.xaml
- Bugfix
Skia Fluent sample for ProgressBar/Ring is blank
Skia Fluent sample for ProgressBar/Ring is not blank
> chore: Disable WinUI ProgressRing Samples for Skia

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ExpandingBottomSheetSamplePage.xaml
GitHub Issue (If applicable): unoplatform/uno#5180
- Bugfix
The xaml source is no longer displayed underneath the toggle button.
> fix: ExpandingBottomSheet page layout

- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/SamplePageLayout.xaml
closes https://github.com/unoplatform/uno/issues/5549
- Bugfix
Native option was cut off and was not selectable
Can now scroll the list of Design Themes to bring the Native RadioButton into view
> fix: Make Design RadioButton list scrollable

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/DatePickerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/PasswordBoxSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/TextBlockSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/TextBoxSamplePage.xaml
- Bugfix
TextBox/ComboBox/DatePicker/TextBlock/PasswordBox Cupertino Samples crashing on UWP because of an invalid Style
Doesn't crash
> fix: Address missing styles causing crashes on UWP

- Uno.Gallery/Uno.Gallery.Shared/Extensions/XamlDisplayExtensions.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/XamlDisplay.xaml
closes https://github.com/unoplatform/Uno.Gallery/issues/212\
- Perf
The Xaml string from ShowMeTheXaml is being formatted by the XamlDisplayExtensions on page load for each XamlDisplay element
Only run formatting logic when displaying the XAML and if the current XAML hasn't been formatted before.
> perf: Avoid eagerly formatting the XAML string for ShowMeTheXaml

- Uno.Gallery/Uno.Gallery.UWP/App.xaml.cs
#213
- Bugfix
Null ref occurring on UWP build since Window.Current.Dispatcher is null in the App ctor
No longer deal with Dispatcher/Analytics calls when not running for WASM
> fix: Only call AnalyticsService for WASM, avoid possible null ref of Dispatcher

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/App.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
- Bugfix
Debug logs who flood the console with Not Implemented exceptions
Console logs are no longer filled with Not Implemented exception messages
> fix: Set NotImplementedLogLevel to Debug to avoid unnecessary console logs

- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/SamplePageLayout.xaml
closes https://github.com/unoplatform/uno/issues/5784
- Bugfix
There is currently a bug on macOS that is causing the StackPanel to be arranged to the size of its Grid row even though all of its children are Visbility=Collapsed. This bug should be fixed by the Grid refactor PR (https://github.com/unoplatform/uno/pull/5811). For now, we avoid the StackPanel from Stretching the entire Grid row and intercepting the pointers.
Pointers are now being handled
> fix: Workaround for sticky tabs StackPanel measure bug

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ComboBoxSamplePage.xaml
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/6073
- Bugfix
The spelling of Combobox is incorrect.
The spelling of Combobox must be correct.
> Fix(ComboBox): Fix the spelling of ComboBox for Uno Gallery

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/App.xaml
- Uno.Gallery/Uno.Gallery.UWP/App.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/CalendarDatePickerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/CalendarDatePickerSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/CalendarViewSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
fixes https://github.com/unoplatform/uno/issues/6211
- Bugfix
DatePicker was on the same page as the CalendarView, causing an overlap of calendar views
Initial selected state of Selection Mode ComboBox appears blank
CalendarDatePicker and CalendarView have their own sample pages now
Initial selected state of Selection Mode ComboBox is Single
> fix(CalendarView): Separate CalendarView/CalendarDatePicker samples. Fix selection mode combbox

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/CalendarViewSamplePage.xaml
- Bugfix
Selecting Multiple selection mode for CalendarView wasn't working
Selection Mode Multiple works
> fix(CalendarView): Fix selection mode binding

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/ToggleSwitch.xaml
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
GitHub Issue (If applicable): #314
- Bugfix
Material ToggleSwitch styles are not displaying correctly on WASM
Material ToggleSwitch styles are now displaying correctly on WASM
> fix(ToggleSwitch): Material styles not displaying correctly on WASM

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Android project file changes
- Enable again AndroidUseAapt2 as https://github.com/unoplatform/uno/issues/1382 is now resolved
- Remove the target that will force the generation of the APK as it's not needed anymore and as it causes issues to deploy on Android with latest VS 2022 Prev 17.1.0 Preview 1.0 and 1.1
> chore(Android): Remove workarounds not needed anymore

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/FlyoutSamplePage.xaml
GitHub Issue (If applicable): #https://github.com/unoplatform/uno/issues/7566
- Bugfix
For the Material Button 'Flyout' sample, the text is overlapping the whole screen and not styled like it should
Update Button FlyoutPresenterStyle in the sample to match the latest style name changes in Uno.Material 
(Related to this commit and breaking change in Uno.Material : https://github.com/unoplatform/Uno.Themes/commit/6a0f105a5b9d120c00a09776beb2290826e1a042)
> fix: Update Button FlyoutPresenterStyle in the sample to match latest changes in Uno.Material 

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/CalendarViewSamplePage.xaml
GitHub Issue (If applicable): closes unoplatform/uno#7023
- Other... Please describe: styling
Minor visual change
Align XamlDisplay style with other controls: "See Xaml" -> "<>"
> fix: CalendarView xaml display style

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
- Bugfix
Bring back mobile/not_mobile XAML namespaces so we can exclude/include certain samples based on platform
>  Bring back mobile/not_mobile XAML namespaces

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/App.xaml
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
GitHub Issue (If applicable):  related issue https://github.com/unoplatform/uno.toolkit.ui/issues/205
- Bugfix
TabBar Sample App Page crashes for UWP
No more TabBar Sample App Page crash for UWP
Fix TabBar Sample App Page crash for UWP and remove MaterialToolkitColors following breaking change with latest Uno.Toolkit.UI breaking change
> fix: TabBar Sample App Page crash for UWP and remove MaterialToolkitColors following breaking change

- LICENSE.md
- README.md
Documentaion
- in Readme, corrected naming from MacOS to macOS
> documentation corrections - MacOS -> macOS

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
GitHub Issue (If applicable): n/a
- Bugfix
Appearance of ghost `mobile` and `not_mobile` files under every head project in solution explorer.
They are hidden from solution explorer.
> fix(csproj): remove ghost mobile and not_mobile files

- Uno.Gallery/Uno.Gallery.UWP/App.xaml
closes #387 
- Bugfix
**A note in the Uno.Themes documentation will be made to address this**
> fix: Initialize Fluent resources after Material resources to maintain Fluent implicit styles

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ButtonSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/XamlDisplay.xaml
GitHub Issue (If applicable): Fixes https://github.com/unoplatform/uno/issues/8991
- Bugfix
Fix Material ElevatedButtonStyle samples not correctly visible in Dark mode in Gallery
> fix: Material ElevatedButtonStyle samples not correctly visible in Dark mode in Gallery

- Uno.Gallery/Uno.Gallery.UWP/Views/GeneralPages/OverviewPage.xaml
GitHub Issue (If applicable): closes unoplatform/uno#9008
- Bugfix
re-enable toggleSwitch sample in Overview
> chore: re-enable toggleSwitch sample in Overview

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- Uno.Gallery/Uno.Gallery.Shared/Controls/SamplePageLayout.Properties.cs
- Uno.Gallery/Uno.Gallery.Shared/Controls/SamplePageLayout.cs
- Uno.Gallery/Uno.Gallery.Shared/Entities/Sample.cs
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/Colors.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/GeneralPages/OverviewPage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ButtonSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ListViewSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/TabBarSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/SamplePageLayout.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/XamlDisplay.xaml
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
GitHub Issue (If applicable): Resolves https://github.com/unoplatform/uno/issues/8840, Resolves https://github.com/unoplatform/uno/issues/8790, Resolves https://github.com/unoplatform/uno/issues/8955, Resolves https://github.com/unoplatform/uno/issues/8989, Resolves https://github.com/unoplatform/uno/issues/8990, Resolves https://github.com/unoplatform/uno/issues/9011
- Bugfix
Fix multiple visual issues for Gallery:
- [Add back the M3 ToggleSwitch sample for the Overview Page](https://github.com/unoplatform/Uno.Gallery/pull/391/commits/3963d04f9cecc47a3a3bcd93e2ee791d0257b14b)
- [Fix Padding issue for the Overview bottom page](https://github.com/unoplatform/Uno.Gallery/pull/391/commits/280e090c3dc8ac8548e1d756e3d8cb2eed3d0611)
- [Update Uno.UI, …
> Fix multiple visual issues for Gallery

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ButtonSamplePage.xaml
GitHub Issue (If applicable): closes unoplatform/uno#9117
- Bugfix
Fluent Button examples for back button are missing their disabled equivalent.
add examples for disabled NavigationBackButton
> chore: add examples for disabled NavigationBackButton

- Uno.Gallery/Uno.Gallery.Mobile/Android/Main.Android.cs
GitHub Issue (If applicable): closes unoplatform/uno#8790
- Bugfix
On net6-droid in release, any DataTemplate/Page using ITextWatcherInvoker under the hood crashes with:
TypeLoadException: Could not load type '{0}' from assembly '{1}'., Android.Text.ITextWatcherInvoker, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
No more crash
`<LinkDescription />` does not work for the `Uno.Gallery.Mobile.csproj`, so `[DynamicDependency]` had to be used instead.
> fix(net6-droid): ITextWatcherInvoker TypeLoadException

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/FileFolderPickerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/FileFolderPickerSamplePage.xaml.cs
GitHub Issue (If applicable): #465 
- Feature
No sample page for file and folder pickers.
A File and Folder Picker sample page has been added.
The sample page includes:
- Opening and saving files in several different scenarios:
+ Opening a single file.
+ Opening multiple files.
+ Opening files of a specific type.
+ Opening a folder.
+ Saving to a file.
+ Saving to multiple files in a folder.
- Code snippets. The code snippets include C# event handlers. The C# code is simplified to allow the user to focus on the UWP File APIs.
> feat: Add File & Folder picker sample

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/AccelerometerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/AccelerometerSamplePage.xaml.cs
GitHub Issue (If applicable): #463 
- Feature
No sample page for `Accelerometer`
A sample page for `Accelerometer` has been added.
The sample page includes:
- Demonstrations for Accelerometer APIs that are implemented in Uno: `GetDefault()`, `ReportInterval`, `Shaken` and `ReadingChanged`. Other APIs that are available in UWP but not Uno are left out.
- A basic C# code snippet that demonstrates the use of `GetDefault()` and the two events.
On an Android 12 phone:
On a Windows 11 PC:
> feat: Add Accelerometer sample page

- Uno.Gallery/Uno.Gallery.UWP/Views/Shell.xaml.cs
GitHub Issue (If applicable): closes #512
- Bugfix
Safe area calculation does not use updated window bounds, which means that window size change cause the resulting top padding to be non-sensical
Use current window bounds always.
> fix: Safe area bounds don't respect Window bounds changes

- Uno.Gallery/Uno.Gallery.Droid/Properties/AndroidManifest.xml
- Uno.Gallery/Uno.Gallery.UWP/Package.appxmanifest
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/GeolocatorSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/GeolocatorSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.iOS/Info.plist
- Uno.Gallery/Uno.Gallery.macOS/Info.plist
Adds the Geolocator sample page.
Includes changes in AndroidManifest.xml, iOS Info.plist and macOS Info.plist, UWP Package.appxmanifest, in order to be able to use the location services in each platform.
GitHub Issue (If applicable): #462 
Feature
No sample page for Geolocator
A sample page for Geolocator has been added.
The sample page includes a demonstration of basic Geolocator usage (with one-time location access and with a monitor on the Geolocator position changed event).
On Android 12 emulator:
On Windows 11 PC:
On WASM:
> feat: Add Geolocator sample page

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/GeolocatorSamplePage.xaml.cs
Adds null checks to the properties used in the UpdateLocation method to avoid NullReferenceException when the location is null.
GitHub Issue (If applicable): #462 
- Bugfix
In some cases the location is null, generating a NullReferenceException.
Prevents the NullReferenceException.
> fix: GeolocatorSamplePage null check on UpdateGeolocation

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/PowerManagerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/PowerManagerSamplePage.xaml.cs
GitHub Issue (If applicable): closes #480
- Feature
The Gallery app does not have a sample for the `PowerManager` API.
The `PowerManager` sample is added for UWP, Android and iOS - the only supported platforms.
Windows 11:
Android 12:
> feat: Add sample for PowerManager

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/FileFolderPickerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/FileFolderPickerSamplePage.xaml.cs
`PickSaveMultipleFiles` now overwrites the `file1.txt` and `file2.txt` if they exist instead of crashing the app.
Fixes https://github.com/unoplatform/uno/issues/10219
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/10219
- Bugfix
App crashes when selecting a folder that already has `file1.txt` or `file2.txt` in the `PickSaveMultipleFiles` example.
Instead of crashing, the app overwrites the existing files.
> fix: Fix PickSaveMultipleFiles crashing app

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/RatingControlSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/RatingControlSamplePage.xaml.cs
Adds the sample page for the RatingControl.
GitHub Issue (If applicable): #448 
- Feature
No sample page for RatingControl.
A sample page for RatingControl has been added.
On Android 12 emulator:
On Windows 11 PC:
On WASM:
> feat: Add RatingControlSamplePage

- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- azure-pipelines.yml
- build/stage-build-android-mobile.yml
- build/templates/dotnet-install-mac.yml
- build/templates/dotnet-install-windows.yml
Partially reverts unoplatform/Uno.Gallery#623 for mobile targets, caused by https://github.com/unoplatform/uno/issues/11044
> Restore net6 targets for mobile

- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/11676
- Bugfix
SVGs are not displayed on SkiaGtk Linux/macOS/Windows.
> fix: Added and updated packages for Skia SVG

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/LampSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/LampSamplePage.xaml.cs
Plus made some minor changes to the code of the sample.
GitHub Issue (If applicable): #665
- Bugfix
The Lamp sample always shows as not supported on WASM. The reason for it is because the API is not implemented on WASM.
The Lamp sample is hidden from the platforms that does not support the API.
> fix: Removed Lamp from unsupported platforms

- .github/workflows/azure-static-webapp.yml
GitHub Issue (If applicable): n/a
Azure Static WebApps failing the pr checks with:
> Reason: This Static Web App already has the maximum number of staging environments (10). Please remove one and try again.
Failure to deploy no longer blocks the PR.
> ci: continue-on-error with static-web-apps-deploy

- Uno.Gallery/Uno.Gallery.UWP/Views/GeneralPages/MaterialPalettePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/ContentPageLayout.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/SamplePageLayout.xaml
GitHub Issue (If applicable): #693
- Bugfix
+ made the sample pages match the spacing of the palette pages
> fix: Adjust spacing across the app

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/CalendarDatePickerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/CalendarViewSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/CardSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/CommandBarSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/GridViewSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/SwipeControlSamplePage.xaml
GitHub Issue (If applicable): #710
- Bugfix
Some pages use different backgrounds and it makes the samples inconsistent in Canary builds. 
> fix: Different backgrounds across samples

- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/TypographyControl.xaml
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/12279
- Bugfix
Text is truncated on small mobile screen sizes. 
The issue has been fixed and it now supports all device screen sizes.
> fix: Typography sample text truncation on small devices

- Uno.Gallery/Uno.Gallery.Shared/Entities/SampleConditionals.cs
- Bugfix
`SampleConditionals.Always.HasFlag(SampleConditionals.Disabled)` is `true`.
`SampleConditionals.Always.HasFlag(SampleConditionals.Disabled)` will be `false`.
`int.MaxValue` doesnt set the bit on where `1 << 31` is on. And then, xor'ing it just set it...
> fix(sample): SampleConditionals.Always includes Disabled

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/AcrylicSamplePage.xaml.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/10828#issuecomment-1428471596
- Bugfix
Acrylic sample is hidden on Skia.
> fix: Hide Acrylic sample on Skia

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/AccelerometerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/AccelerometerSamplePage.xaml.cs
GitHub Issue (If applicable): 
closes https://github.com/unoplatform/uno/issues/10217
- Bugfix
The 
Accelerometer sample (page) crashes when reading the values.
> fix(iOS): accelerometer sample page crash

- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/MediaPlayerElementSample_NestedPage1.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/MediaPlayerElementSample_NestedPage2.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/MediaPlayerElementSample_NestedPage3.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/MediaPlayerElementSample_NestedPage4.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/MediaPlayerElementSample_NestedPage5.xaml.cs
GitHub Issue (If applicable):
https://github.com/unoplatform/uno/issues/12638
- Bugfix
In the current version the video continues to play when changing samples.
Note:- The sound of the video is not working.
Current behaviour is the Audio of the played video keep on playing even close all the options.
To close the music need to kill Gallery app and relaunch it.
Now the video stop to play when change the samples.
> [Gallery][Android] MediaPlayerElement the Audio of the played video keeps on running for the first and third 'show sample' option.

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/InfoBadgeSamplePage.xaml.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/12402
- Bugfix
- Opacity slider displays numeric values for 0.6 and more.
- Added rounding function to setter.
> fix: infobadge opacity slider

- Uno.Gallery/Uno.Gallery.Shared/Extensions/XamlDisplayExtensions.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/BreadcrumbBarSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ColorPickerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/InfoBadgeSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/RatingControlSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/RatingControlSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/XamlDisplay.xaml
GitHub Issue (If applicable): #766
Added an optional Options panel to XamlDisplay. This reduces the redundancy of the current control+options setup in the samples.
- Feature
> feat: Add sample Options

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/TwoPaneViewSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/TwoPaneViewSamplePage.xaml.cs
GitHub Issue (If applicable): #753
- Bugfix
TwoPaneView from WUXC is used, which is not supported by Uno.
Switched to MUXC TwoPaneView.
> fix: Use MUXC TwoPaneView

- Uno.Gallery/Uno.Gallery.Shared/Extensions/XamlDisplayExtensions.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/TreeViewSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/XamlDisplay.xaml
GitHub Issue (If applicable): #812 
- Bugfix
The TreeView sample doesn't use the new Options in XamlDisplay.
Made the TreeView to use Options. Updated the flexibility of the Options panel and removed the Options from the displayed output string.
> chore: Update TreeView to use Options

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/TextBlockSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/TextBlockSamplePage.xaml.cs
GitHub Issue (If applicable): #805
- Bugfix
The TextBlock sample has a Cupertino style which showcases the same things as Typography page and doesn't make much sense.
Removed the Cupertino style from the sample and made it design agnostic.
> chore: Remove Cupertino TextBlock

- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- Uno.Gallery/Uno.Gallery.Shared/App.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/Styles/SamplePageLayout.xaml
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.Windows/Uno.Gallery.Windows.csproj
closes https://github.com/unoplatform/Uno.Gallery/issues/831
Design systems may be using the same resource keys, this causes a problem given that the Gallery itself is using Uno.Material but we also need to be able to display Fluent components as well as Material components in the "sample area". The sample area should load the proper resources for whichever design system it is displaying rather than relying on the styles being initialized globally at the app level
> fix: load proper design theme resources per tab

- Uno.Gallery/Uno.Gallery.Shared/Views/NestedPages/MediaPlayerElementSample_NestedPage5.xaml.cs
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/MediaPlayerElementSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/MediaPlayerElementSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
https://github.com/unoplatform/uno/issues/12653
- Bugfix
When click close button, mediaplayer window for Customizable option should get close.
When click close button, after try to enter on the MPE sample playlist, and enter in other sample mediaplayer window, as Customizable option, the window should get close.
Feature items/playlist is just implemented for ANDROID || IOS || MACOS
So in the Sample 5 (Playlist) we just show the first video.
And as requested we disable the feature on unsupported platform, so the Sample 5, playlist, do not show on other platforms.
And i added the references to test the MediaPlayer Skia on windows
Internal Issue (If …
> [Gallery][Wasm] MediaPlayerElement, [X] Close button does not work for customizable option once click on the last sample option.

- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- build/stage-uitests-android.yml
- build/stage-uitests-ios.yml
- build/templates/dotnet-install-mac.yml
- build/templates/dotnet-install-windows.yml
Now that Toolkit supports Shadows, it requires newer workload versions as a result of skiasharp dependencies so we need to bump Gallery
> ci: bump uno-check to 1.13.0

- build/sign-package.ps1
Msix package for Windows is not properly signed
Msix package for Windows is properly signed
> fix: sign-package ps script after switch to WinUI for the Sample App

- Uno.Gallery/Uno.Gallery.Shared/Views/GeneralPages/OverviewPage.xaml
[Closes #11428](https://github.com/unoplatform/uno/issues/11428)
- Bugfix
It doesnt have any text 
Add some text to describe the toggle swith like there is with the other controls
I did not put the text to the right of the control, because on some platform, even if you remove the minimum Width, it still takes 200 points of space.
What it looks like: 
Expected look from issue:
> fix: add missing toggle switch description in Overviewpage

- build/4x-overrides.json
GitHub Issue (If applicable): #n/a
Certain packages weren't pinned to 4.x, and are bumped to 5.x during canary update process...
They are now pinned.
> build: adjust legacy canary updater overrides

- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- Uno.Gallery/Uno.Gallery.Shared/Converters/HexToColorConverter.cs
- Uno.Gallery/Uno.Gallery.Shared/Selectors/NeumorphicTemplateSelector.cs
- Uno.Gallery/Uno.Gallery.Shared/Uno.Gallery.Shared.projitems
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/ShadowContainerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/ShadowContainerSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.Shared/Views/Styles/NeumorphicStyles.xaml
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.Windows/Uno.Gallery.Windows.csproj
- Rework Shadow showcase to show one control at a time
- Add the Shadow Builder control sample
Default state:
Control selected:
> Shadows showcase (refactor neumorphic styles, add shadow builder)

- Uno.Gallery/Uno.Gallery.Shared/App.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/Styles/FluentOverrides.xaml
closes https://github.com/unoplatform/uno/issues/13398
`XamlControlsResources` does not include the default implicit styles for `muxc:` controls, they need to be explicitly re-defined in order to override the Material ones
> fix: properly override implicit styles for muxc controls

- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- Uno.Gallery/Uno.Gallery.Shared/Views/GeneralPages/OverviewPage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/Styles/SamplePageLayout.xaml
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.Windows/Uno.Gallery.Windows.csproj
https://github.com/unoplatform/Uno.Gallery/issues/901
- Bugfix
- Fix CheckBox, RadioButton, and ToggleSwitch controls labels not matching like it should
- Fix InteropServices.COMException - Cannot locate resource from 'ms-resource:///Files/FluentOverrides.xaml'
- Update Material/Cupertino packages
> fix: CheckBox, RadioButton and ToggleSwitch controls labels not matching like it should

- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/ShadowContainerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/ShadowContainerSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.Windows/Uno.Gallery.Windows.csproj
Issue: https://github.com/unoplatform/uno.toolkit.ui/issues/798
PR: https://github.com/unoplatform/uno.toolkit.ui/pull/807
Now when the Calculator remove the item, the size is not been resized.
When we remove items, the size is been updated.
> Change ItemsControl for ItemsRepeater

- Uno.Gallery/Uno.Gallery.Shared/Views/Styles/NeumorphicStyles.xaml
https://github.com/unoplatform/uno/issues/13557
- Bugfix
When you click the checkbox, it clicks the checkbox twice, making it look like it was not cliked on on android.
It the click is only registered once, so it changes from checked to unchecked everytime you click on it.
> fix: checkbox double click

- Uno.Gallery/Uno.Gallery.Shared/Extensions/XamlDisplayExtensions.cs
GitHub Issue (If applicable): close unoplatform/ShowMeTheXAML#28
- Bugfix
- xmlns declarations wont appear on attached property anymore
- xmlns declarations are now all grouped at the start of document, like:
```xml
xmlns:um="using:Uno.Material"
...
<Button>
<um:ControlExtensions.Icon>
<PathIcon Data="..." />
<um:ControlExtensions.Icon>
</Button>
```
> fix(smtx): invalid xmlns declaration on attached property

- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
Update Svg.Skia version to align with minimum version enforced by https://github.com/unoplatform/uno/pull/13722
> build: update svg.skia

- Uno.Gallery/Uno.Gallery.Shared/Views/Colors.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/ButtonSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/ClipboardSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/DisplayRequestSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/ElevatedViewSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/LocalSettingsSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/PasswordVaultSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/SharingSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/SimpleOrientationSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/TwoPaneViewSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/VibrationDeviceSamplePage.xaml
GitHub Issue (If applicable): #974
- Bugfix
Certain pages with ApplicationPageBackgroundThemeBrush used at the page or page root level, can randomly fail to theme-switch properly.
Should not happen anymore.
> chore: workaround for theme-switching rng failure

- .github/workflows/azure-static-webapp.yml
- build/stage-build-mobile.yml
- build/stage-build-windows.yml
- build/templates/gitversion.yml
Bump versions for Net Core Runtime and gitversion to fix the CI Builds and match Uno core versions
> ci: Bump versions for Net Core Runtime and gitversion to fix the CI Builds

- Uno.Gallery/Uno.Gallery.Shared/Views/Shell.xaml
GitHub Issue (If applicable): re #945
- Bugfix
tweak web-banner to be closer to https://platform.uno/ :
- adjust buttons text font/size
- v-center dropdown button chevron & thicken it
- add cta button animation
> fix: tweak web-banner visual

- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/DatePickerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/DatePickerSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/TimePickerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/TimePickerSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.Windows/Uno.Gallery.Windows.csproj
- Feature
feat: Enable TimePicker and DatePicker samples for all platforms 
(now that the support was added in Uno core - https://github.com/unoplatform/uno/pull/14097)
- TimePicker example with fluent button as well as fluent style picker on Android:
- TimePicker example with fluent button and native picker on Android:
> feat: Enable TimePicker and DatePicker samples for all platforms

- Uno.Gallery/Uno.Gallery.UITest/Constants.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_RadioButton_02_Fluent.cs
- Uno.Gallery/Uno.Gallery.UITest/TestBase.cs
GitHub Issue (If applicable): closes # 
- Bugfix
- Feature
> feat: developing UI test for radio button.

- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/PasswordBoxSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UITest/Given_PasswordBox_Cupertino.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_PasswordBox_Fluent.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_PasswordBox_Material.cs
> feat: creating Ui test for passwordbox

- Uno.Gallery/Uno.Gallery.Shared/Views/Styles/SamplePageLayout.xaml
- Bugfix
Android/iOS (DatePicker - Native Tab)
For the native tab, the DatePicker button is using Material style instead of Fluent by default
Added Fluent override for the NativeTemplate to avoid seeing material styles for the native tab by default
> fix: Added Fluent override for the NativeTemplate to avoid seeing material styles for the native tab by default

- Directory.Packages.props
- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- Remove duplicate PackageReference for Uno.Extensions.Logging.OSLog for net7.0-ios and net7.0-maccatalyst conditions as this reference is already added for every platform
- Update SkiaSharp.Views.Uno.WinUI to latest stable
> chore: Remove duplicate PackageReference for Uno.Extensions.Logging.OSLog and update SkiaSharp.Views.Uno.WinUI to latest stable

- README.md
`AppStore` (incorrect) -> `App Store` (correct)
Confusingly, Amazon's store is named "AppStore" 🤗
> docs: Readme 'App Store' naming correction

- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/LightweightStylingSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/RadioButtonSamplePage.xaml
Closes #1109 
- Bugfix
- Fix RadioButton GroupName for the LightweightStyling FluentTemplate
- Remove unnecessary SecondaryRadioButtonStyle sample as it was part of Material v1 and removed in v2
> Fix RadioButton GroupName for the LightweightStyling FluentTemplate & remove unnecessary SecondaryRadioButtonStyle

- Uno.Gallery/Uno.Gallery.UITest/Given_AutoSuggestBox.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_NumberBox.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_PasswordBox_Material.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_RadioButton_02_Fluent.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_RatingControl.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_TextBox.cs
> test: Fix build errors in RadioButton UI tests

- .github/workflows/azure-static-webapp.yml
- Directory.Packages.props
- Uno.Gallery/Uno.Gallery.Mobile/Android/AndroidManifest.xml
- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UITest/Uno.Gallery.UITest.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.Windows/Properties/PublishProfiles/win-arm64.pubxml
- Uno.Gallery/Uno.Gallery.Windows/Properties/PublishProfiles/win-x64.pubxml
- Uno.Gallery/Uno.Gallery.Windows/Properties/PublishProfiles/win-x86.pubxml
- Uno.Gallery/Uno.Gallery.Windows/Uno.Gallery.Windows.csproj
- azure-pipelines.yml
- build/scripts/android-uitest-run.sh
- build/scripts/ios-uitest-run.sh
- build/scripts/wasm-uitest-run.sh
- build/stage-build-android-mobile.yml
- build/stage-build-skia-gtk.yml
- build/stage-build-wasm.yml
- build/stage-build-windows.yml
- build/stage-uitests-ios.yml
- build/stage-uitests-wasm.yml
- build/templates/canary-updater.yml
- build/templates/dotnet-install-mac.yml
- build/templates/dotnet-install-windows.yml
> build: Update to net8.0 to fix canary

- azure-pipelines.yml
- build/stage-uitests-wasm.yml
Canary builds are timing out. Let's see if that will fix it.
- Bugfix
- Feature
> ci: Increase timeout

- Uno.Gallery/Uno.Gallery.Shared/Views/Styles/NeumorphicStyles.xaml
GitHub Issue (If applicable): closes #1106
- Bugfix
This should fix the issue with https://github.com/unoplatform/Uno.Gallery/issues/1106, once this https://github.com/unoplatform/uno.toolkit.ui/pull/1142 PR is merged.
> fix: TabbarItem with Neumorphic Style crash on Windows

- Uno.Gallery/Uno.Gallery.Shared/Views/Shell.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/Shell.xaml.cs
GitHub Issue (If applicable): closes #1122
- Bugfix
fix search result visuals
part of https://github.com/unoplatform/Uno.Gallery/issues/1122
> chore: Improve search experience

- Uno.Gallery/Uno.Gallery.Shared/Views/Shell.xaml
- scripts/wasm banner source-gen.linq
GitHub Issue (If applicable): closes #1132
- Bugfix
typo and outdated links in the web banner
updated web banner links to be in sync with platform.uno
added script to sync links from platform.uno
> chore: update wasm banner nav items

- Uno.Gallery.UITests/Given_RadioButton_02_Fluent.cs
- Uno.Gallery/Uno.Gallery.csproj
- build/stage-uitests-wasm.yml
GitHub Issue (If applicable): closes #1154, closes #1156
- Bugfix
- Feature
> build: Add tsconfig.json to ConfigFiles item

- Directory.Build.props
> fix: Remove pinned versions

- Uno.Gallery/Views/SamplePages/TextBoxSamplePage.xaml
GitHub Issue (If applicable): closes https://github.com/unoplatform/Uno.Themes/issues/1457
- Bugfix
The Outlined `TextBox` that should be disabled is enabled.
The Outlined `TextBox` that should be disabled is now disabled.
> fix: Outlined TextBox Disabled

- Uno.Gallery/Views/SamplePages/TextBoxSamplePage.xaml
GitHub Issue (If applicable): closes https://github.com/unoplatform/Uno.Themes/issues/1461
- Bugfix
TextBox playground is not responsive
TextBox playground is responsive
> fix: Make TextBox playground responsive

- Uno.Gallery/Uno.Gallery.csproj
Fixing errors from latest winappsdk 1.6:
C:\Users\VssAdministrator\.nuget\packages\microsoft.windowsappsdk\1.6.240829007\buildTransitive\Microsoft.WindowsAppSDK.targets(76,9): error : This version of the Windows App SDK requires Microsoft.Windows.SDK.NET.Ref 10.0.19041.38 or later. [D:\a\1\s\Uno.Gallery\Uno.Gallery.csproj]
C:\Users\VssAdministrator\.nuget\packages\microsoft.windowsappsdk\1.6.240829007\buildTransitive\Microsoft.WindowsAppSDK.targets(76,9): error :     Please update to .NET SDK 6.0.134, 6.0.426, 8.0.109, 8.0.305 or 8.0.402 (or later). [D:\a\1\s\Uno.Gallery\Uno.Gallery.csproj]
C:\Users\VssAdministrator\.nuget\packages\microsoft.windowsappsdk\1.6.240829007\buildTransitive\Microsoft.WindowsAppSDK.targets(76,9): error :     Or add a temporary Microsoft.Windows.SDK.NET.Ref …
> build: add windowssdkpackageversion

- Uno.Gallery/Views/SamplePages/AutoSuggestBoxSamplePage.xaml.cs
https://github.com/unoplatform/uno/issues/15967
Forces Fluent style on AutosuggestBox popup in Wasm.
- Bugfix
Autosuggest box has Material styles applied.
When the page loads gets the Border's popup control via `GetTemplateChild` and applies `EnsureXamlControlsResources()` method.
I got the name of the Border from the microsoft repo.
https://github.com/microsoft/microsoft-ui-xaml/blob/d74a0332cf0d5e58f12eddce1070fa7a79b4c2db/src/controls/dev/AutoSuggestBox/AutoSuggestBoxHelper.cpp#L8-L13
https://github.com/unoplatform/uno/issues/15967
> fix: Ensure Fluent resources for AutoSuggestBox on WASM

- Uno.Gallery/Views/SamplePages/SimpleOrientationSamplePage.xaml.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/17688
- Bugfix
Gallery iOS Application crashes when using the SimpleOrientationSensor sample page
> fix(iOS): SimpleOrientationSensor Sample Crash

- Uno.Gallery.UITests/Given_Card_01.cs
- Uno.Gallery.UITests/Given_RadioButton_02_Fluent.cs
- Uno.Gallery/App.xaml.cs
- Uno.Gallery/Uno.Gallery.csproj
- azure-pipelines.yml
- build/scripts/android-uitest-run.sh
- build/scripts/android-uitest-wait-systemui.sh
- build/stage-uitests-android.yml
- build/templates/canary-updater.yml
Adjust for occasional emulator startup issues that cause retries.
- Don't assume the order of ANR process reporting
- Terminate the system UI preemptively in order to restart clean after boot
> Misc android and canary updates

- Uno.Gallery/Controls/SamplePageLayout.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1291
- Bugfix
- Feature
> fix: work around Visual offset delays when ViewChanged is fired

- Uno.Gallery/Views/SamplePages/SwipeControlSamplePage.xaml
GitHub Issue (If applicable): n/a
- Bugfix
App failing to compile:
> error CS0103: The name '__ResourceOwner_2' does not exist in the current context
workaround applied to make the app compile.
for context: unoplatform/uno#19745
> chore: workaround for __ResourceOwner_2 build errors

- Uno.Gallery/Extensions/XamlDisplayExtensions.cs
- Uno.Gallery/Views/Styles/XamlDisplay.xaml
GitHub Issue (If applicable): #1196
- Bugfix
In ShowMeTheXaml, the indentation level for text literal is higher than it should
The formatter will now fix the indentation based on the node depth.
ninja-fix: changed indentation from 3spaces to 4spaces
> fix(smtx): text-literal indentation
