- azure-pipelines.yml
> ci: Fix Android NDK Paths

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- azure-pipelines.yml
> ci: Build APK for appcenter

- Uno.Gallery/Uno.Gallery.iOS/Info.plist
- Uno.Gallery/Uno.Gallery.macOS/Info.plist
closes https://github.com/unoplatform/uno/issues/5093
- Bugfix
> fix(iOS): Custom fonts

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
GitHub Issue (If applicable): fix #111
- Bugfix
Cant scroll through nav-view items on uwp.
Fixed.
> fix(uwp): nav-view items not scrollable

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ModalStandardBottomSheetSamplePage.xaml
GitHub Issue (If applicable): fixes #136 
- Bugfix
Broken layout
Improved layout
> fix: Layout of modal standard bottom sheet page

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ExpandingBottomSheetSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/StandardBottomSheetSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/XamlDisplay.xaml
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5181
- Bugfix
Code snippets are cut
Code snippets are no longer cut
> Do not limit code snippet height, improve sheet sample formatting

- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
Disabling profiled AOT until https://github.com/unoplatform/uno/issues/4613 issues are fixed
> fix(reg): Disable PG-AOT

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ToggleSwitchSamplePage.xaml
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5179
- Bugfix
- 
Snippet does not display.
Displays
> fix: Show ToggleSwitch fluent styles source code snippet

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/WebViewSamplePage.xaml.cs
GitHub Issue (If applicable): fixes #151
- Feature
macOS WebView not in samples
macOS WebView in samples
> feat: Add WebView sample for macOS

- Uno.Gallery/Uno.Gallery.macOS/Info.plist
> fix(macOS): Crash at start up

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ProgressSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
- Feature
No Material/Determinate ProgressRing samples
Has Material + Determinate ProgressRing samples
> feat: Add ProgressRing Samples

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/FlyoutSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/TextBlockSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/TextBoxSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/TypographySamplePage.xaml
> fix: Break up long text to workaround macOS issue

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
- Other... Please describe: Update  Uno.UI to the latest
> chore: Update Uno to the  latest (3.6.0)

- Uno.Gallery/Uno.Gallery.Shared/Entities/Sample.cs
- Uno.Gallery/Uno.Gallery.UWP/App.xaml.cs
https://github.com/unoplatform/uno/issues/5108
Release logs contain a bunch of Not Implemented in Uno failure messages
Release logs do not contain a bunch of Not Implemented in Uno failure messages
> Reduce amount of failure logs in Release mode

- azure-pipelines.yml
> chore: Add xamarin.mac ci workaround

- Uno.Gallery/Uno.Gallery.UITest/Extensions.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_CheckBox.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_MainPage.cs
- Uno.Gallery/Uno.Gallery.UITest/TestBase.cs
- Uno.Gallery/Uno.Gallery.UITest/Uno.Gallery.UITest.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/Shell.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/NavigationView.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/SamplePageLayout.xaml
> feat(UITest): Add more test helper methods

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
> Update Uno packages

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
> chore: Update Uno.Material

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/DatePickerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/DatePickerSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
closes https://github.com/unoplatform/uno/issues/5321
- Feature
Add DatePicker sample using new and improved WinUI DatePicker
> feat(DatePicker): Add new DatePicker sample

- Uno.Gallery/Uno.Gallery.UITest/Extensions.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_CheckBox.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_MainPage.cs
- Uno.Gallery/Uno.Gallery.UITest/TestBase.cs
- Uno.Gallery/Uno.Gallery.UWP/App.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/Shell.xaml.cs
> test: Refactor test sample page navigation

- azure-pipelines.yml
Removing workaround for macOS CI build as it is no longer needed
> ci: Remove macOS Workaround

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
> chore: Update uno

- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/ToggleSwitch.xaml
closes https://github.com/unoplatform/uno/issues/5562
- Bugfix
> fix: Add ToggleSwitch WASM CornerRadius workaround

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
> chore: update Uno packages

- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
Restores mixed-mode AOT after recent dotnet runtime fixes.
> ci: restore Mixed-mode AOT

- Uno.Gallery/Uno.Gallery.UWP/App.xaml.cs
> perf: Dispatch analytics calls to Idle Dispatcher

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
GitHub Issue (If applicable): https://github.com/unoplatform/Uno.Themes/issues/574
- Bugfix
[ToggleSwitch] Some states don't match Material Design guidelines
All states match Material Design guidelines for all platforms
> chore: Update Uno.Material and Uno.Cupertino

- Uno.Gallery/Uno.Gallery.macOS/Info.plist
closes https://github.com/unoplatform/uno/issues/5938
- Bugfix
> fix(Fonts): [macOS] Fix font path

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
closes https://github.com/unoplatform/uno/issues/5941
> chore: Update packages

- Uno.Gallery/Uno.Gallery.UWP/App.xaml.cs
- Uno.Gallery/Uno.Gallery.Wasm/WasmScripts/branch.js
https://github.com/unoplatform/Uno.Gallery/issues/256
- Feature
> feat(Deeplinking): Add Branch deeplinking to WASM

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UITest/Given_CalendarView.cs
- Uno.Gallery/Uno.Gallery.UWP/App.xaml
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/CalendarViewSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/CalendarViewSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/Button.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/XamlDisplay.xaml
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
https://github.com/unoplatform/Uno.Themes/issues/577
- Feature
> Add CalendarView/CalendarDatePicker samples

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
GitHub Issue (If applicable): fixes https://github.com/unoplatform/uno/issues/5874
- Bugfix
Updating Uno.Material and Uno.Cupertino packages in order to fix the https://github.com/unoplatform/uno/issues/5874 issue.
> chore: Update Uno.Material and Uno.Cupertino packages

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
> chore: Update to uno latest

- .github/workflows/azure-static-webapp.yml
Enable azure static webapps PR validation for Uno.Gallery
> ci: Enable azure static webapps PR validation for Uno.Gallery

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Shared/Uno.Gallery.Shared.projitems
- Uno.Gallery/Uno.Gallery.Shared/ViewModels/Command.cs
- Uno.Gallery/Uno.Gallery.Shared/ViewModels/ViewModelBase.cs
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/App.xaml
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/CupertinoBottomBarSampleNestedPage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/CupertinoBottomBarSampleNestedPage.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/MaterialBottomBarSampleNestedPage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/MaterialBottomBarSampleNestedPage.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/MaterialTopBarSampleNestedPage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/MaterialTopBarSampleNestedPage.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/TabBarSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/TabBarSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
> Add tabbar sample

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/GeneralPages/FluentPalettePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/GeneralPages/MaterialPalettePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/CupertinoBottomBarSampleNestedPage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/CupertinoBottomBarSampleNestedPage.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/MaterialBottomBarSampleNestedPage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/MaterialBottomBarSampleNestedPage.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/MaterialTopBarSampleNestedPage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/NavigationBarSample_NestedPage1.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/NavigationBarSample_NestedPage2.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/CardSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ChipGroupSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ChipGroupSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ChipSamplePage.xaml.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ChipSamplePage.xaml.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/DividerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/TabBarSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/ContentPageLayout.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/SamplePageLayout.xaml
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
Adjust Uno.Toolkit.UI namespaces with latest package
> chore: Adjust Uno.Toolkit.UI namespaces with latest package

- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/MaterialTopBarSampleNestedPage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/MaterialTopBarSampleNestedPage.xaml.cs
> fix: Don't use TabBarSelectorBehavior for sample

- Uno.Gallery/Uno.Gallery.UWP/App.xaml
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/SegmentedControlSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/SegmentedControlSamplePage.xaml.cs
> Add SegmentedControl sample

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/App.xaml
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/Colors.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/GeneralPages/FluentPalettePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/GeneralPages/MaterialPalettePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/GeneralPages/OverviewPage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ChipGroupSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ComboBoxSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/DividerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/FabSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/TextBoxSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/ContentPageLayout.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/NavigationView.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/SamplePageLayout.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/ToggleButton.xaml
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
Adjust namespaces related to latest Uno packages
> refactor: Adjust namespaces related to latest Uno packages

- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/NavigationView.xaml
GitHub Issue (If applicable): Fixes unoplatform/uno#8028
- Bugfix
Burger menu can close but cannot reopen on all platforms
Burger menu can now be closed and reopened again on all platforms
Related to previous commit change here :
https://github.com/unoplatform/Uno.Gallery/pull/338/commits/17f64a893c48c02d1675d85a385dd43985def71a
> fix: Burger menu can now be closed and reopened again

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UITest/Constants.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_Card_01.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_CheckBox_01_Material.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_CheckBox_02_Material_Secondary.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_CheckBox_03_Fluent.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_CheckBox_04_Cupertino.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_RadioButton_01_Material.cs
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/CardSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
- Project Automation
N/A
Added UI automation scripts for Card 
> test: New UI automation script for Card control

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
Related to https://github.com/xamarin/xamarin-android/issues/7352
> fix: Disable LLVM on android for VS 17.3 issue

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/RefreshContainerPage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/RefreshContainerPage.xaml.cs
> feat: RefreshContainer sample

- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ClipboardSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ClipboardSamplePage.xaml.cs
- build/stage-build-android-mobile.yml
- build/stage-build-android-xamarin.yml
- build/stage-build-ios-xamarin.yml
- build/stage-build-mobile.yml
GitHub Issue (If applicable): #464
- Feature
No Clipboard sample page.
A Clipboard sample page has been added.
The sample page includes:
- Copying and pasting of different data types (text, image, rich text, and files).
- Managing the Clipboard (flush, clear, and content changed).
- Code snippets.
The file example is disabled on every platform except UWP and Skia because there is no known support.
Furthermore, attempting to get the files from the `Assets` folder on some platforms (Android) throws an exception.
Note that the samples on WASM other than text won't work due to https://github.com/unoplatform/uno/issues/10032.
Because I don't own an iPhone, I cannot test the app on iOS, but …
> feat: Add Clipboard Sample Page

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/PasswordVaultSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/PasswordVaultSamplePage.xaml.cs
GitHub Issue (If applicable): #495
- Sample
No sample for `PasswordVault`.
A sample for `PasswordVault`.
> feat: Add Sample for `PasswordVault`-API

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/SimpleOrientationSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/SimpleOrientationSamplePage.xaml.cs
GitHub Issue (If applicable): #479 
- Sample
There is no sample for `SimpleOrientationSensor`.
There is a sample for `SimpleOrientationSensor`.
> feat: Add `SimpleOrientationSensor`-Sample

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/SharingSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/SharingSamplePage.xaml.cs
GitHub Issue (If applicable): #490
- Sample
There is not sample for the sharing UI.
There is a sample for the sharing UI.
> feat: Add sharing sample page

- Uno.Gallery/Uno.Gallery.Droid/Properties/AndroidManifest.xml
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/NetworkInformationSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/NetworkInformationSamplePage.xaml.cs
GitHub Issue (If applicable): #461 
- Sample
There is not sample for `NetworkInformation`.
There is a sample for `NetworkInformation`.
> feat: Add sample for `NetworkInformation`

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/LocalSettingsSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/LocalSettingsSamplePage.xaml.cs
GitHub Issue (If applicable): #492
- Sample
There is no sample for `LocalSettings`.
There is now a sample for `LocalSettings`.
> feat: Add `LocalSettings`-Sample

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/DisplayRequestSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/DisplayRequestSamplePage.xaml.cs
GitHub Issue (If applicable): #481
- Sample
There is no sample for `DisplayRequest`.
There is a sample for `DisplayRequest`.
> feat: Add `DisplayRequest`-Sample

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/LightSensorSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/LightSensorSamplePage.xaml.cs
GitHub Issue (If applicable): #477
- Sample
There is no sample for the `LightSensor`.
There is a sample for the `LightSensor`.
> feat: Add `LightSensor`-sample

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/MenuBarSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/MenuBarSamplePage.xaml.cs
- add sample for simple menu bar
- add sample with keyboard accelerators
- add sample for submenus, seperators and toggle
- add sample with icons
GitHub Issue (If applicable): #449 
> add MenuBar sample page

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/RelativePanelSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/RelativePanelSamplePage.xaml.cs
- add sample for default position
- add sample with vertical alignment
- add sample with horizontal alignment
- add sample with complex alignment
- add sample with a border
GitHub Issue (If applicable): #453 
> add RelativePanel sample page

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/PhoneCallManagerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/PhoneCallManagerSamplePage.xaml.cs
GitHub Issue (If applicable): #493 
- Feature
There is no sample for PhoneCallManager.
There is now a sample for PhoneCallManager.
Screenshot from Android:
Screenshot from WASM:
> feat: Add sample for PhoneCallManager

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/EmailManagerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/EmailManagerSamplePage.xaml.cs
Adds the EmailManager sample page.
GitHub Issue (If applicable): #485 
- Feature
No sample page for EmailManager.
A sample page for EmailManager has been added.
On Android 12 emulator:
On Windows 11 PC:
On WASM:
> feat: Add EmailManager sample page

- Uno.Gallery/Uno.Gallery.UWP/App.xaml
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/InfoBadgeSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/InfoBadgeSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/InfoBadge.xaml
Adds the InfoBadgeSamplePage with usage examples of InfoBadge control.
GitHub Issue (If applicable): #451 
- Feature
No sample page for InfoBadge.
A sample page for InfoBadge has been added.
On Android 12 emulator:
On Windows 11 PC:
On WASM:
> feat: Add InfoBadgeSamplePage

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/HingeAngleSensorPage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/HingeAngleSensorPage.xaml.cs
GitHub Issue (If applicable): #476 
- Sample
There is no sample of usage of HingleAngleSensor on dual-screen devices.
There is a working sample for HingleAngleSensor.
It's working!
https://user-images.githubusercontent.com/1633261/197856332-67eae157-37c9-437b-9ece-ded861a59204.mp4
> feat: Add HingeAngleSensor sample page

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/NumberBoxSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/NumberBoxSamplePage.xaml.cs
GitHub Issue (If applicable): fixes #450 
> add sample page for NumberBox

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/LampSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/LampSamplePage.xaml.cs
GitHub Issue (If applicable): #471
- Sample
There is no sample for Lamp.
There is a sample usage of a Lamp (flashlight).
> feat: Add Lamp usage sample

- README.md
GitHub Issue (If applicable): fixes #24 
> edit readme - added links to the gallery website and store pages

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/GridSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/GridSamplePage.xaml.cs
GitHub Issue (If applicable): fixes #562 
> add sample page for Grid

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/MagnetometerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/MagnetometerSamplePage.xaml.cs
GitHub Issue (If applicable): #470 
- Sample
There is no sample for Magnetometer.
There is a sample for Magnetometer.
https://user-images.githubusercontent.com/1633261/197861074-ebcd7e67-8466-4b11-8c72-d8e108597308.mp4
> feat: Add Magnetometer sample

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/TwoPaneViewSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/TwoPaneViewSamplePage.xaml.cs
GitHub Issue (If applicable): fixes #457 
> add sample page for TwoPaneView

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/StackPanelSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/StackPanelSamplePage.xaml.cs
GitHub Issue (If applicable): fixes #563 
- Feature /sample page
> add sample page for StackPanel

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/SwipeControlSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/SwipeControlSamplePage.xaml.cs
GitHub Issue (If applicable): https://github.com/unoplatform/uno/issues/6894
- Feature
No samples for SwipeControl
Add samples for SwipeControl which are adapted from Microsoft's XCG source
FYI: I tested these samples and SwipeControl doesn't seem to work correctly on WASM.
Internal Issue (If applicable): N/A
> feat: SwipeControl samples

- Uno.Gallery/Uno.Gallery.UWP/Views/GeneralPages/FluentPalettePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/GeneralPages/MaterialPalettePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/AcrylicSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/CardSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/DividerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ElevatedViewSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/InfoBarSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ListViewSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/SwipeControlSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ToggleSwitchSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/TransformsSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/ViewBoxSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/Banner.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/ColorPaletteView.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/ContentPageLayout.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/NavigationView.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/OverviewSampleView.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/RadioButton.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/SamplePageLayout.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/ThreeColorPaletteView.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/ToggleButton.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/ToggleSwitch.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/XamlDisplay.xaml
closes https://github.com/unoplatform/uno/issues/10783
closes https://github.com/unoplatform/Uno.Gallery/issues/625
> fix: Use ThemeResource for Material brushes

- Uno.Gallery/Uno.Gallery.Mobile/Android/AndroidManifest.xml
GitHub Issue (If applicable): might fix https://github.com/unoplatform/uno/issues/11180, not sure.
- Bugfix
- Feature
> fix: Add missing permissions to AndroidManifest.xml

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/GamepadSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/GamepadSamplePage.xaml.cs
GitHub Issue (If applicable): #501
- Feature
The Gallery does not have a sample for the Gamepad API.
Added the Gamepad API sample.
> Add Gamepad API sample

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/EmailManagerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/EmailManagerSamplePage.xaml.cs
GitHub Issue (If applicable): #656
- Bugfix
- Design improvements
Minor design improvements on the EmailManager page. Also added a little easter egg. 
> fix: EmailManager spacing and design improvements

- Uno.Gallery/Uno.Gallery.Wasm/WasmScripts/AppManifest.js
GitHub Issue (If applicable): #662
- Feature
The Splash Screen is always bright.
The Splash Screen reflects the users browser/OS theme.
> feat: Theme-Aware Splash Screen

- Uno.Gallery/Uno.Gallery.UWP/App.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/Shell.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Shell.xaml.cs
GitHub Issue (If applicable): #648
- Feature
There is currently no way to search through the available samples, which makes it hard to find the one you are looking for.
https://user-images.githubusercontent.com/78549750/224848443-066308d0-4d17-473d-a848-66d71afdc0d5.mp4
The AutoSuggestBox is currently only available in Fluent. After the [Material version](https://github.com/unoplatform/Uno.Themes/issues/638) is added, we could update it as well to match the overall aesthetics of the app.
> feat: Add samples Search

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/InfoBadgeSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/InfoBadgeSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/InfoBadge.xaml
GitHub Issue (If applicable): #657
- Bugfix
https://user-images.githubusercontent.com/78549750/226122378-3fea3966-088d-4b11-b364-fea3af5f1a64.mp4
https://user-images.githubusercontent.com/78549750/226122289-b315744f-6f43-4efc-894b-0b46ada13e36.mp4
> fix: InfoBadge sample design improvements

- Uno.Gallery/Uno.Gallery.Shared/Converters/FromObjectToValueConverter.cs
- Uno.Gallery/Uno.Gallery.Shared/Uno.Gallery.Shared.projitems
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/Converters.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/AutoSuggestBoxSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/AutoSuggestBoxSamplePage.xaml.cs
GitHub Issue (If applicable): #668
- Feature
Gallery does not have a AutoSuggestBox sample.
https://user-images.githubusercontent.com/78549750/229382522-b1a9e4d2-da19-4791-814c-c3c4e93c887a.mp4
> feat: Added AutoSuggestBox sample

- Uno.Gallery/Uno.Gallery.Droid/Properties/AndroidManifest.xml
- Uno.Gallery/Uno.Gallery.Mobile/Android/AndroidManifest.xml
- Uno.Gallery/Uno.Gallery.Mobile/iOS/Info.plist
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/LauncherSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/LauncherSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.iOS/Info.plist
GitHub Issue (If applicable): #482
- Feature
There is no sample page for the Launcher API.
Added Launcher API sample.
> feat: Added Launcher API sample

- Uno.Gallery/Uno.Gallery.Shared/Controls/TypographyControl.cs
- Uno.Gallery/Uno.Gallery.Shared/Uno.Gallery.Shared.projitems
- Uno.Gallery/Uno.Gallery.UWP/App.xaml
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/TypographySamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/Styles/TypographyControl.xaml
GitHub Issue (If applicable): #683
- Bugfix
> fix: Typography sample design improvements

- Uno.Gallery/Uno.Gallery.Droid/Properties/AndroidManifest.xml
- Uno.Gallery/Uno.Gallery.Mobile/Android/AndroidManifest.xml
- Uno.Gallery/Uno.Gallery.Mobile/iOS/Info.plist
- Uno.Gallery/Uno.Gallery.UWP/Package.appxmanifest
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/PedometerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/PedometerSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.iOS/Info.plist
GitHub Issue (If applicable): #478
- Feature
Added Pedometer sample.
> feat: Add Pedometer sample

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/GyrometerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/GyrometerSamplePage.xaml.cs
GitHub Issue (If applicable): #475
- Feature
Added `Gyrometer` sample. 
> feat: Add Gyrometer sample

- Uno.Gallery/Uno.Gallery.Shared/Entities/Data/Folder.cs
- Uno.Gallery/Uno.Gallery.Shared/Uno.Gallery.Shared.projitems
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/BreadcrumbBarSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/BreadcrumbBarSamplePage.xaml.cs
GitHub Issue (If applicable): #456
- Feature
https://github.com/unoplatform/Uno.Gallery/assets/78549750/92cda442-b56b-44d2-adaa-1b863d156183
> feat: Add BreadcrumbBar sample

- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/MediaPlayerElementSample_NestedPage5.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/MediaPlayerElementSample_NestedPage5.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/MediaPlayerElementSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/MediaPlayerElementSamplePage.xaml.cs
- Feature
Add a MediaPlayerElement sample using a playlist
> feat: Add a MediaPlayerElement sample using a playlist

- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/GyrometerSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/PedometerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/PedometerSamplePage.xaml.cs
GitHub Issue (If applicable): closes #730
- Bugfix
fixed 2 instances of crash related to pedometer & gyrometer
> misc fixes

- azure-pipelines.yml
- Build or CI-related changes
Add a variable group for Authenticode Sign Packages for UWP
> ci: Use variable group for Authenticode Sign Packages

- Uno.Gallery/Uno.Gallery.Droid/Uno.Gallery.Droid.csproj
- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/MediaPlayerElementSample_NestedPage1.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/MediaPlayerElementSample_NestedPage2.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/MediaPlayerElementSample_NestedPage3.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/MediaPlayerElementSample_NestedPage4.xaml
- Uno.Gallery/Uno.Gallery.UWP/Views/NestedPages/MediaPlayerElementSample_NestedPage5.xaml
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.iOS/Uno.Gallery.iOS.csproj
- Uno.Gallery/Uno.Gallery.macOS/Uno.Gallery.macOS.csproj
- Bugfix
MediaPlayerElement samples cannot be tested properly on some small devices
Adjustments made to MediaPlayerElement samples so it is easier to test them on all devices
> fix: Make adjustments to MediaPlayerElement samples so it is easier to test them on all devices

- azure-pipelines.yml
- build/stage-uitests-android.yml
The auto-retry will take care of re-running jobs
> ci: Adjust timeouts

- Directory.Build.props
> build: Disable XAML fuzzy matching

- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Program.cs
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UWP/Uno.Gallery.UWP.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
> chore(deps): Update Uno version

- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/ToggleSwitchSamplePage.xaml
#837 
- Feature
The sample doesnt include toggleswitch with icons
There are now some toggle switch with icons in the sample.
> feat: update toggle switch material sample to include icon

- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/LightweightStylingSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/LightweightStylingSamplePage.xaml.cs
GitHub Issue (If applicable): #824 
- Feature
Created a sample page for lightweight styling override:
Material
Fluent
> feat: Lightweight Styling sample page

- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/ToggleSwitchSamplePage.xaml
- build/sign-package.ps1
GitHub Issue (If applicable): #13157
- Bugfix
- Other... Please describe: Chore
Lottie not working correctly on WASM
Lottie working correctly on WASM
https://github.com/unoplatform/uno/issues/13157
> Updates canaries/4x with legacy/4x

- build/4x-overrides.json
> chore: Use 7.999.999 for wasm bootstrap [legacy/4x]

- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- Uno.Gallery/Uno.Gallery.Shared/Views/NestedPages/MediaPlayerElementSample_NestedPage5.xaml.cs
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.Windows/Uno.Gallery.Windows.csproj
GitHub Issue (If applicable): #12394
- Bugfix
- Feature
- Bugfix
MediaPlayerElement sample using a playlist not working
MediaPlayerElement sample using a playlist working
update uno.ui package to 2127
> Fix MediaPlayerElement sample using a playlist not working

- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- Uno.Gallery/Uno.Gallery.Shared/Views/NeumorphicColorsOverride.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/ShadowContainerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/ShadowContainerSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.Shared/Views/Styles/NeumorphicStyles.xaml
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.Windows/Uno.Gallery.Windows.csproj
> feat: Adding neumorphic styles

- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/TransformsSamplePage.xaml
GitHub Issue (If applicable): 
closes https://github.com/unoplatform/uno/issues/7540
- Bugfix
> fix: Corrected rotated square margin on Transforms page

- Uno.Gallery/Uno.Gallery.Shared/Views/Styles/NeumorphicStyles.xaml
GitHub Issue (If applicable): #899
> fix: Adding proper StateOverlay for TabBarItem

- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/ShadowContainerSamplePage.xaml
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/13450, closes https://github.com/unoplatform/uno/issues/13449
- Bugfix
- Feature
> chore: Fix spelling in ShadowContainer page and add missing IsThreeState for indeterminate

- Settings.XamlStyler
- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- Uno.Gallery/Uno.Gallery.Shared/Views/NeumorphicColorsOverride.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/Styles/NeumorphicStyles.xaml
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UITest/Uno.Gallery.UITest.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.Windows/Uno.Gallery.Windows.csproj
GitHub Issue (If applicable): re: #931
closes #912, closes #914, 
- Bugfix
update neumorphic control styles as per design
> style: update neumorphic control styles

- Uno.Gallery/Uno.Gallery.Shared/App.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/Styles/SamplePageLayout.xaml
> fix: change init order of fluent/material

- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/GeolocatorSamplePage.xaml
Validating if this update causes any change to the issue reported for iOS 17 and some buttons.
- Bugfix
> fix(iOS): Geolocactor sample button iOS17

- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- Uno.Gallery/Uno.Gallery.Shared/Views/NeumorphicColorsOverride.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/Styles/NeumorphicStyles.xaml
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.Windows/Uno.Gallery.Windows.csproj
GitHub Issue (If applicable): re: #931
closes #913 (replacing #922)
- Bugfix
> neumorphic styles follow up update

- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/ShadowContainerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/Styles/NeumorphicStyles.xaml
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.Windows/Uno.Gallery.Windows.csproj
fixes https://github.com/unoplatform/Uno.Gallery/issues/935
> feat: Add Neumorphic styles to Shadow Builder sample

- Uno.Gallery/Uno.Gallery.Mobile/Android/AndroidManifest.xml
- Uno.Gallery/Uno.Gallery.Mobile/MacCatalyst/Base.lproj/InfoPlist.strings
- Uno.Gallery/Uno.Gallery.Mobile/MacCatalyst/Info.plist
- build/stage-build-windows.yml
- build/templates/canary-updater.yml
- build/templates/dotnet-install-mac.yml
- build/templates/dotnet-install-windows.yml
- Build using Android 33
- Adjust Catalyst app name
> Misc publication fixes

- Uno.Gallery/Uno.Gallery.Shared/Views/Styles/NeumorphicStyles.xaml
GitHub Issue (If applicable): #913
- Bugfix
Adjusted brushes for:
- ComboBox: leading icon, arrow icon, placeholder and selected item text
- TextBox: leading icon, delete button, placeholder and text
- PasswordBox: Leading icon, visibility button and placeholder
> Adjust ComboBox TextBox PasswordBox style

- Uno.Gallery/Uno.Gallery.Shared/Views/Styles/NeumorphicStyles.xaml
GitHub Issue (If applicable): #931
- Bugfix
> fix: Adjusting ToggleSwitch shadows details

- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/ShadowContainerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/Styles/NeumorphicStyles.xaml
Adding changes for Slider and removing Theme colors not used anymore.
> chore: neu- slider style

- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/ShadowContainerSamplePage.xaml
> fix: remove unneeded extra shadow from builder

- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/GridSamplePage.xaml
closes https://github.com/unoplatform/Uno.Gallery/issues/896
- Bugfix
-  Tested on Wasm.
-  Tested on Android.
- Tested on UWP.
- Tested in both **Light** and **Dark** themes.
-  Associated with an issue (GitHub or internal)
https://github.com/unoplatform/Uno.Gallery/issues/896
> fix: textbox issue in Grid

- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/SliderSamplePage.xaml
GitHub Issue (If applicable): #988 
- Bugfix
Sliders are inverted.
> chore: Change `Slider` orientation

- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- Uno.Gallery/Uno.Gallery.Shared/Converters/DateTimeToDateTimeOffsetConverter.cs
- Uno.Gallery/Uno.Gallery.Shared/Converters/FromValueToStringConverter.cs
- Uno.Gallery/Uno.Gallery.Shared/Entities/Data/Plant.cs
- Uno.Gallery/Uno.Gallery.Shared/Entities/SampleCategory.cs
- Uno.Gallery/Uno.Gallery.Shared/Uno.Gallery.Shared.projitems
- Uno.Gallery/Uno.Gallery.Shared/Uno.Gallery.Shared.shproj
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/DataGridSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/DataGridSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UITest/Uno.Gallery.UITest.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.Windows/Uno.Gallery.Windows.csproj
GitHub Issue (If applicable): closes #691 
- Feature
Added `DataGrid` from the Windows Community Toolkit. And the Community Toolkit to the Navigation.
Added the package `Uno.CommunityToolkit.WinUI.UI.Controls.DataGrid` version 7.1.200-dev.13.gef3f523648
An internal discussion with Martin and Sasha.
> feat: Add WCT `DataGrid` sample

- .github/workflows/azure-static-webapp.yml
> ci: Update .NET SDK

- Uno.Gallery/Uno.Gallery.Shared/Converters/SecretConverter.cs
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/CalendarDatePickerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/ShadowContainerSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/ShadowContainerSamplePage.xaml.cs
- Other: DotNetConf 2023 Treasure Hunt 2023
> feat: Treasure Hunt 2023

- Uno.Gallery/Uno.Gallery.UITest/Uno.Gallery.UITest.csproj
The version of Uno.UITest.Helpers was 1.1.0-dev.59
The new version of Uno.UITest.Helpers is the latest version which we can have.
> feat: updating the Uno.UITest.Helpers 

- Directory.Packages.props
- Uno.Gallery.SourceGenerators/Uno.Gallery.SourceGenerators.csproj
- Uno.Gallery.sln
- Uno.Gallery/Uno.Gallery.Mobile/Uno.Gallery.Mobile.csproj
- Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj
- Uno.Gallery/Uno.Gallery.UITest/Uno.Gallery.UITest.csproj
- Uno.Gallery/Uno.Gallery.Wasm/Uno.Gallery.Wasm.csproj
- Uno.Gallery/Uno.Gallery.Windows/Uno.Gallery.Windows.csproj
> build: use cpm

- build/stage-build-android-mobile.yml
- build/stage-build-mobile.yml
- build/stage-build-skia-gtk.yml
- build/stage-build-wasm.yml
- build/stage-build-windows.yml
closes https://github.com/unoplatform/Uno.Gallery/issues/1076
- Bugfix
> ci: fix gitversion informationalversion

- Uno.Gallery/Uno.Gallery.UITest/Constants.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_Card_01.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_RadioButton_01_Material.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_RadioButton_02_Fluent.cs
- Uno.Gallery/Uno.Gallery.UITest/Given_RadioButton_03_Cupertino.cs
- Uno.Gallery/Uno.Gallery.UITest/TestBase.cs
> Creating UI test for gallery 

- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/LightweightStylingSamplePage.xaml
> fix: remove confusing lightweight styling overrides

- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/AutoSuggestBoxSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UITest/Given_AutoSuggestBox.cs
> feat: introducing UI test for AutoSuggestBox

- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/TextBoxSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UITest/Given_TextBox.cs
> feat: ui test for textbox

- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/RatingControlSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UITest/Given_RatingControl.cs
> feat: creating UI test for rating control

- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/NumberBoxSamplePage.xaml
- Uno.Gallery/Uno.Gallery.UITest/Given_NumberBox.cs
> feat: automating the ui test for number box

- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/AcrylicSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/AcrylicSamplePage.xaml.cs
> feat: Sample for `AcrylicBrush` tint

- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/TeachingTipSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/TeachingTipSamplePage.xaml.cs
> feat: `TeachingTip` sample

- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/GeolocatorSamplePage.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/GeolocatorSamplePage.xaml.cs
Fixed the following issues in the Geolocator sample page:
A. GetGeoposition button vertical alignment
B. Geolocator description
A. The content of the GetGeoposition button is aligned to the top.
B. The description says, "This sensor returns latitude, longitude, *longitude* and accuracy".
A. The content is aligned to the center.
B. The description says, "This sensor returns latitude, longitude, *altitude* and accuracy".
> fix: Fix trivial issues in the Geolocator sample page

- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/TransformsSamplePage.xaml
Removed the space in each header so it matches its corresponding type and be consistent with other pages.
"Scale Transform", "Rotate Transform", "Translate Transform", "Skew Transform"
"ScaleTransform", "RotateTransform", "TranslateTransform", "SkewTransform"
> fix: Update headers for consistency with other pages

- Uno.Gallery/Uno.Gallery.Shared/App.xaml.cs
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/AccelerometerSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/GamepadSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/GeolocatorSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/LauncherSamplePage.xaml.cs
- Uno.Gallery/Uno.Gallery.Shared/Views/SamplePages/PhoneCallManagerSamplePage.xaml.cs
> build: Fix some build warnings

- Uno.Gallery/Uno.Gallery.Shared/Views/Shell.xaml
- Uno.Gallery/Uno.Gallery.Shared/Views/Shell.xaml.cs
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/17396
- Bugfix
- Feature
Adds behavior on the Search icon for the SamplesSearch. Fixes bug where the popup disappears when the icon is clicked.  
> feat: Add QuerySubmitted behavior on SamplesSearch

- Uno.Gallery/Views/SamplePages/TextBoxSamplePage.xaml
> chore: Add TextBox combinations

- Uno.Gallery/Entities/Sample.cs
> fix: Ensure ViewType is set before calling CreateData

- Uno.Gallery/Platforms/WebAssembly/LinkerConfig.xml
> fix: Fix LinkerConfig after single project migration

- .gitignore
- Directory.Packages.props
- Uno.Gallery.UITests/Uno.Gallery.UITests.csproj
- Uno.Gallery/App.xaml.cs
- Uno.Gallery/Platforms/WebAssembly/tsconfig.json
- Uno.Gallery/Uno.Gallery.csproj
- build/stage-uitests-android.yml
- build/stage-uitests-ios.yml
- build/stage-uitests-wasm.yml
> ci: Fail CI probably when no test results are available

- Uno.Gallery/Helpers/SystemThemeHelper.cs
- global.json
> chore(deps): Update Uno.Sdk

- .github/workflows/azure-static-webapp.yml
> ci: Update upload-artifact to v4

- build/scripts/android-uitest-run.sh
> ci: android test changes fix path

- Uno.Gallery/Views/SamplePages/FlipViewSamplePage.xaml
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1162
- Bugfix
> fix: Replace `FlipView` glyphs and UI

- Uno.Gallery/Views/SamplePages/FileFolderPickerSamplePage.xaml
- Uno.Gallery/Views/SamplePages/FileFolderPickerSamplePage.xaml.cs
- global.json
GitHub Issue (If applicable): closes https://github.com/unoplatform/private/issues/585
- Bugfix
Broken
Fixed
> Adjust support for folder and file picker samples

- Directory.Build.props
- Uno.Gallery/App.xaml.cs
- Uno.Gallery/Controls/OverviewSampleView.cs
- Uno.Gallery/Views/NestedPages/CommandBarSample_NestedMaterialPage1.xaml.cs
- Uno.Gallery/Views/NestedPages/CupertinoBottomBarSampleNestedPage.xaml.cs
- Uno.Gallery/Views/NestedPages/MaterialBottomBarSampleNestedPage.xaml.cs
- Uno.Gallery/Views/NestedPages/MaterialTopBarSampleNestedPage.xaml.cs
- Uno.Gallery/Views/NestedPages/MediaPlayerElementSample_NestedPage1.xaml.cs
- Uno.Gallery/Views/NestedPages/MediaPlayerElementSample_NestedPage2.xaml.cs
- Uno.Gallery/Views/NestedPages/MediaPlayerElementSample_NestedPage3.xaml.cs
- Uno.Gallery/Views/NestedPages/MediaPlayerElementSample_NestedPage4.xaml.cs
- Uno.Gallery/Views/NestedPages/MediaPlayerElementSample_NestedPage5.xaml.cs
- Uno.Gallery/Views/NestedPages/NavigationBarSample_NestedPage1.xaml.cs
- Uno.Gallery/Views/SamplePages/CommandBarSamplePage.xaml.cs
- Uno.Gallery/Views/SamplePages/MediaPlayerElementSamplePage.xaml.cs
- Uno.Gallery/Views/SamplePages/NavigationBarSamplePage.xaml.cs
- Uno.Gallery/Views/SamplePages/TabBarSamplePage.xaml.cs
- Uno.Gallery/Views/Shell.xaml
- Uno.Gallery/Views/Shell.xaml.cs
> feat: Add multi-window support

- Uno.Gallery/App.xaml.cs
- Uno.Gallery/Views/NestedPages/CommandBarSample_NestedMaterialPage1.xaml.cs
- Uno.Gallery/Views/NestedPages/CupertinoBottomBarSampleNestedPage.xaml.cs
- Uno.Gallery/Views/NestedPages/MaterialBottomBarSampleNestedPage.xaml.cs
- Uno.Gallery/Views/NestedPages/MaterialTopBarSampleNestedPage.xaml.cs
- Uno.Gallery/Views/NestedPages/MediaPlayerElementSample_NestedPage1.xaml.cs
- Uno.Gallery/Views/NestedPages/MediaPlayerElementSample_NestedPage2.xaml.cs
- Uno.Gallery/Views/NestedPages/MediaPlayerElementSample_NestedPage3.xaml.cs
- Uno.Gallery/Views/NestedPages/MediaPlayerElementSample_NestedPage4.xaml.cs
- Uno.Gallery/Views/NestedPages/MediaPlayerElementSample_NestedPage5.xaml.cs
- Uno.Gallery/Views/NestedPages/NavigationBarSample_NestedPage1.xaml.cs
- Uno.Gallery/Views/SamplePages/CommandBarSamplePage.xaml.cs
- Uno.Gallery/Views/SamplePages/MediaPlayerElementSamplePage.xaml.cs
- Uno.Gallery/Views/SamplePages/NavigationBarSamplePage.xaml.cs
- Uno.Gallery/Views/SamplePages/TabBarSamplePage.xaml.cs
- Uno.Gallery/Views/Shell.xaml.cs
> fix: Avoid Window.Current

- Uno.Gallery/Entities/SourceSdk.cs
- Uno.Gallery/Views/Shell.xaml
- Uno.Gallery/Views/Shell.xaml.cs
- global.json
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/20718
- Feature
New window button is always shown
New window button is shown only on Desktop
> Enable new window button only conditionally

- global.json
> chore: bump uno

- azure-pipelines.yml
Bump to Xcode 16.3 to adjust for actions/runner-images#12541
> ci: adjust xcode for macos-15
